# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'locationTrackerTax' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for locationTrackerTax

  pod 'Firebase/Core'
  pod 'GoogleSignIn'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

end

target 'locationTrackerTax-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for locationTrackerTax-tvOS

  target 'locationTrackerTax-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
